### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'qualification_input.txt.output'

### ISSUE THREAD

**Issue by Darrenzeng** [destwang/CTC2021#1]
I would like to ask the author encountered “FileNotFoundError: [Errno 2] No such file or directory: 'qualification_input.txt.output'”? If met, can you tell me how to solve it?

**Comment by destwang** [comment]
可以检查一下run_bert_ctc2021.sh中predict.py是否成功运行，成功运行后会生成qualification_input.txt.output文件。

**Comment by Darrenzeng** [comment]
不能，我们尝试了多次，但几乎都卡在这里：Traceback (most recent call last):
  File "predict.py", line 123, in <module>
    main(args)
  File "predict.py", line 48, in main
    weigths=args.weights)
  File "/home/dwwb/PycharmProjects/duibudui/ctc_gector/gector/gec_model.py", line 74, in __init__
    self.vocab = Vocabulary.from_files(vocab_path)
  File "/home/dwwb/.local/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 324, in from_files
    vocab.set_from_file(filename, is_padded, namespace=namespace)
  File "/home/dwwb/.local/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 378, in set_from_file
    assert self._oov_token in self._token_to_index[namespace], "OOV token not found!"
AssertionError: OOV token not found!

**Comment by 1250658183** [comment]
我们遇到了相似的问题，报错如下：
Namespace: d_tags
Token: INCORRECT
Traceback (most recent call last):
  File "/home/anaconda3/envs/gector/lib/python3.7/site-packages/allennlp/data/vocabulary.py", line 630, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'
python-BaseException

请问是否是gector的版本问题呢，作者能否提供一个本地使用的gector版本的链接？或者是否是我们的bash脚本设置方法有问题？

**Comment by destwang** [comment]
已经更新Baseline部分代码，安装说明安装后，导入模型即可直接运行。

**Comment by 1250658183** [comment]
@destwang 再次打扰，我已经按照新的新版的baseline代码进行尝试，并按照sh脚本将/ctc2021_baseline以及dev.input放在代码的同级目录下，但是之前遇到的问题似乎仍没有解决，当前仍会触发：
ctc2021_baseline weights_name
Namespace: d_tags
Token: INCORRECT
Traceback (most recent call last):
  File "predict.py", line 116, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "/data1/CTC2021/gector/gector/gec_model.py", line 92, in __init__
    confidence=self.confidence
  File "/data1/CTC2021/gector/gector/seq2labels_model.py", line 74, in __init__
    namespace=detect_namespace)
  File "/home/data_ti4_c/anaconda3/envs/gector/lib/python3.6/site-packages/allennlp/data/vocabulary.py", line 630, in get_token_index
    return self._token_to_index[namespace][self._oov_token]
KeyError: '@@UNKNOWN@@'

这似乎是allennlp的问题，我们当前的库版本按照GECToR的要求，如下：
torch==1.3.0
transformers=2.2.2
scikit-learn==0.20.0
sentencepiece==0.1.91
python-levenshtein==0.12.0
allennlp==0.8.4
overrides==4.1.2 
这是否与basemodel的requirements相同呢？任何可能的帮助都将万分感谢！！

**Comment by destwang** [comment]
上传了requirements.txt，与GECToR的版本一致。
我试着重新创建了一个虚拟环境，运行没有问题。步骤如下：
1. git clone git@github.com:destwang/CTC2021.git
2. conda create -n ctc_gector python=3.6
3. conda activate ctc_gector
4. pip install -r requirements.txt
5. 将模型和dev_input.txt拷入ctc_gector
6. sh run_bert_ctc2021.sh

看你的报错好像是词典有问题，词典在data目录下，可以进行检查看看

**Comment by Darrenzeng** [comment]
> 上传了requirements.txt，与GECToR的版本一致。
> 我试着重新创建了一个虚拟环境，运行没有问题。步骤如下：
> 
> 1. git clone [git@github.com](mailto:git@github.com):destwang/CTC2021.git
> 2. conda create -n ctc_gector python=3.6
> 3. conda activate ctc_gector
> 4. pip install -r requirements.txt
> 5. 将模型和dev_input.txt拷入ctc_gector
> 6. sh run_bert_ctc2021.sh
> 
> 看你的报错好像是词典有问题，词典在data目录下，可以进行检查看看

我重新按照你的这个步骤配置了，我的cuda版本是11.2，但是当我运行sh run_bert_ctc2021.sh或者我单独去调试predict.py时都会遇见一个问题：RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc。我实在没有想通我哪里配置有问题。迫不得已再次咨询下，谢谢
ps:我在cuda10.2上尝试会说cuda版本过低

**Comment by Darrenzeng** [comment]
> 上传了requirements.txt，与GECToR的版本一致。
> 我试着重新创建了一个虚拟环境，运行没有问题。步骤如下：
> 
> 1. git clone [git@github.com](mailto:git@github.com):destwang/CTC2021.git
> 2. conda create -n ctc_gector python=3.6
> 3. conda activate ctc_gector
> 4. pip install -r requirements.txt
> 5. 将模型和dev_input.txt拷入ctc_gector
> 6. sh run_bert_ctc2021.sh
> 
> 看你的报错好像是词典有问题，词典在data目录下，可以进行检查看看

我们尝试着按照您说的步骤在cuda11.2上重新建立了环境，但是仍然在测试时出现问题，当运行sh run_bert_ctc2021.sh或者单独调试predict.py时，会在文件bert_token_embedder.py中的以下代码块：
#         all_encoder_layers = self.bert_model(
#             input_ids=util.combine_initial_dims(input_ids),
#             attention_mask=util.combine_initial_dims(input_mask),
#         )[0]

出现一个问题：RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc
我们尝试着用原生Bert_base_chinese来替换以检测错误，在这里就不报错了，但是在其他地方还是有bug。
ps:我们还尝试使用cuda:10.2来测试代码，但是提示cuda版本过低。

**Comment by destwang** [comment]
@Darrenzeng 
我这边测试环境cuda版本10.2，driver version: 440
cuda版本过低是什么提示？

**Comment by Darrenzeng** [comment]
> @Darrenzeng
> 我这边测试环境cuda版本10.2，driver version: 440
> cuda版本过低是什么提示？

The NVIDIA driver on your system is too old(found version 10000).
Please update your GPU driver by downloading and installing a new version from the URL:http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a Pytorch version that has been compiled with your version of CUDA driver

**Comment by destwang** [comment]
> > @Darrenzeng
> > 我这边测试环境cuda版本10.2，driver version: 440
> > cuda版本过低是什么提示？
> 
> The NVIDIA driver on your system is too old(found version 10000).
> Please update your GPU driver by downloading and installing a new version from the URL:http://www.nvidia.com/Download/index.aspx
> Alternatively, go to: https://pytorch.org to install
> a Pytorch version that has been compiled with your version of CUDA driver

可以检查一下驱动的版本，cuda版本和pytorch版本。
下边链接有驱动版本和cuda版本对照表
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html

使用如下命令查看pytorch对应的cuda版本：
python -c "import torch; print(torch.version.cuda)"
