### ISSUE TITLE
请问比赛最后有举行交流会吗？

### ISSUE THREAD

**Issue by GTSeventeEn** [destwang/CTC2021#10]
请问比赛最后有举行交流会吗？想要学习一下其他思路

**Comment by destwang** [comment]
因为疫情原因，最终比赛未举办交流会。可以关注哈工大讯飞联合实验室（HFL）公众号，上边最新关于CTC文本纠错比赛的结束宣传稿上提供了部分参赛队伍的解决方案报告。
