### ISSUE TITLE
请问这个数据集的详细和baseline性能实验结果有以论文形式放出来吗

### ISSUE THREAD

**Issue by piglaker** [destwang/CTC2021#13]
哥们哥们，求一个paper地址

**Comment by destwang** [comment]
你好，比赛的overview论文已经提交到arxiv上，这两天应该就会发布出来。公开之后会再进行通知，谢谢！

**Comment by destwang** [comment]
论文见https://arxiv.org/pdf/2208.05681.pdf，引用参考如下：

@article{wang2022ctc,
  title={Overview of CTC 2021: Chinese Text Correction for Native Speakers},
  author={Zhao, Honghong and Wang, Baoxin and Wu, Dayong and Che, Wanxiang and Chen, Zhigang and Wang, Shijin},
  journal={arXiv preprint arXiv:2208.05681},
  year={2022}
}
