### ISSUE TITLE
提交得分为-0.999999

### ISSUE THREAD

**Issue by dawnranger** [destwang/CTC2021#2]
按照要求的格式提交了结果，但是得分为-0.999999,

查看scoring output log，显示日志为：

======= Set 1 (Qua): score(set1_score)=ERROR ======= 
list index out of range

**Comment by nalanwaner** [comment]
list index out of range可能是压缩文件中没有找到相应的.predict文件导致的，需要注意压缩文件时不要保留文件夹。

得分为-0.999999还可能是文件格式存在问题，多逗号或少逗号，如“pid=00979, 37, 缺失, , ,,”

**Comment by dawnranger** [comment]
感谢回复，将文件后缀修改为.predict之后就正常了。
