### ISSUE TITLE
请问训练模型的超参和bash里面提供的一致吗？

### ISSUE THREAD

**Issue by YouranShan** [destwang/CTC2021#3]
我们训练复现的模型的结果和baseline的结果差挺大的，请问超参和bash里面提供的一致吗？

**Comment by destwang** [comment]
Baseline模型训练参数和bash中提供的一致，你们复现效果具体是多少？
注意事项：
训练前数据需要进行tokenize，然后使用预处理脚本处理成gector的输入格式，同时需要使用Google的中文BERT模型作为初始化模型。

**Comment by YouranShan** [comment]
用的roberta-wwm和bash参数之后是8.99分，后来换成邮件中提供的baseline效果还变低了

**Comment by destwang** [comment]
> 用的roberta-wwm和bash参数之后是8.99分，后来换成邮件中提供的baseline效果还变低了，不过当时用的是代码对训练集自动生成的vocabulary，所以可能是vocabulary的原因？

很可能是，需要使用本项目提供的vocabulary。
