### ISSUE TITLE
关于两次提供的验证集数据的差异问题

### ISSUE THREAD

**Issue by GTSeventeEn** [destwang/CTC2021#5]
## 内容
8月6号邮件提供的验证集数据qua_input.txt文件中语句数目为972条，与从codalab竞赛网站中下载的资格赛数据qua_input文件985条数目不符。
另外，经过对比除了缺少13条语句外，存在其他句子改动。
下图中：左侧为8月6号数据，右侧为从竞赛网站下载的数据。
![image](https://user-images.githubusercontent.com/38148626/128618104-d8ee6cd7-9c25-4553-a586-99d5f1053563.png)
--------------------------------------------------------
请问1. 资格赛排行榜上的qua_input文件的句子数目是哪个？
2.是否可以提供一下评估F1值得分的代码？我们在编写评估代码时，不确定是数据差异或是代码bug，所以无法定位评估代码问题。

**Comment by destwang** [comment]
你好，因为资格赛数据为人工标注的真实数据，其中难免有些错误和漏标。本次开放的验证集在资格赛数据基础上又进行了一轮人工校验，修复了其中部分错误。资格赛排行榜上句子数目为985条，评测脚本我们稍后会进行开放。
